### ISSUE TITLE
Improve the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-m-m-e#1]
Really cool job @m-m-e  !!!

Here you have some tips to improve the exercise:

- [x] Use ONE `addEventListener` for each event. If you need to execute multiple functions at once perhaps you can call them inside your unique handler
- [x] You are writing many times "trackEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'trackEl'?
 Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by m-m-e** [comment]
Thanks @oneeyedman ! I've corrected those mistakes and added a few extra things... let me know what you think! :smile:

**Comment by oneeyedman** [comment]
Super good job, @m-m-e !

If you are up to a challenge check out these exercises from previous Adalabers:

- http://beta.adalab.es/dorcas-s2-evaluacion-intermedia-mariavioleta1417/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-maria-badanina/
- http://beta.adalab.es/dorcar-s2-evaluacion-intermedia-annabranco/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-beatrizAdalab/

;)

Here you have a cool gif:
![well done](https://media.giphy.com/media/lvOnlEYunAwOkHjgmU/giphy-downsized.gif)
